export const styles = {
  splitScreen: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#1f1f1f",
    color: "#fff",
  },
  leftPane: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "2rem",
  },
  rightPane: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#121212",
    position: "relative",
    overflow: "hidden",
  },
  logoWrapper: {
    position: "absolute",
    right: "5%",
    top: "50%",
    transform: "translateY(-50%)",
    maxHeight: "90vh",
  },
  logoImage: {
    width: "100%",
    maxWidth: "500px",
    height: "auto",
    objectFit: "contain",
    boxShadow: "0 0 30px rgba(0,0,0,0.6)", 
    borderRadius: "12px", 
  },
  fullScreen: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    backgroundColor: "#1f1f1f",
    color: "#fff",
    padding: "2rem",
    boxSizing: "border-box",
  },
  centeredBox: {
    textAlign: "center",
    maxWidth: "600px",
    width: "100%",
    padding: "2rem",
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: "12px",
    boxShadow: "0 0 20px rgba(0,0,0,0.4)",
  },
  button: {
    padding: "0.7rem 1.2rem",
    margin: "0.5rem",
    fontSize: "1rem",
    cursor: "pointer",
    borderRadius: "8px",
    backgroundColor: "#3f51b5",
    color: "#fff",
    border: "none",
    transition: "all 0.3s ease",
  },
  buttonHover: {
    transform: "translateY(-2px)",
    boxShadow: "0 4px 8px rgba(0,0,0,0.2)",
  },
  input: {
    display: "block",
    width: "100%",
    padding: "0.8rem",
    margin: "0.5rem 0",
    borderRadius: "8px",
    border: "1px solid #ccc",
    fontSize: "1rem",
    backgroundColor: "rgba(255,255,255,0.1)",
    color: "#fff",
  },
  cardContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(5, 220px)",
    justifyContent: "start",
    gap: "1rem",
    marginTop: "1rem",
    padding: "0 1rem",
  },
  flipCardContainer: {
    perspective: "1000px",
    width: "220px",
    height: "300px",
  },
  flipCard: {
    position: "relative",
    width: "100%",
    height: "100%",
    transformStyle: "preserve-3d",
    transition: "transform 0.6s",
  },
  flipCardFront: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backfaceVisibility: "hidden",
    backgroundColor: "#1f1f1f",
    color: "#ffffff",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "2rem",
    fontWeight: "bold",
    border: "1px solid #ccc",
    borderRadius: "8px",
    boxShadow: "0 2px 5px rgba(0,0,0,0.4)",
  },
  flipCardBack: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backfaceVisibility: "hidden",
    transform: "rotateY(180deg)",
    color: "#ffffff",
    textShadow: "-1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    border: "1px solid #ccc",
    borderRadius: "8px",
    boxShadow: "0 2px 5px rgba(0,0,0,0.4)",
    cursor: "pointer",
  },
  packCard: {
    border: "1px solid #ccc",
    padding: "1rem",
    borderRadius: "8px",
    width: "220px",
    height: "300px",
    fontSize: "1rem",
    backgroundColor: "#1f1f1f",
    color: "#ffffff",
    boxShadow: "0 2px 5px rgba(0,0,0,0.4)",
    cursor: "pointer",
    gap: "1rem",
  },
  teamCard: {
    width: "200px",
    height: "320px",
    border: "1px solid #ccc",
    padding: "0.5rem",
    borderRadius: "8px",
    fontSize: "0.8rem",
    backgroundColor: "#1f1f1f",
    color: "#ffffff",
    boxShadow: "0 2px 5px rgba(0,0,0,0.4)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    textAlign: "center",
    lineHeight: "0.5",
    textShadow: "-1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000",
  },
  fullPageCentered: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    width: "100vw", 
    backgroundColor: "#1f1f1f",
    color: "#fff",
    textAlign: "center",
    padding: "2rem",
    boxSizing: "border-box",
  },
  stackContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center", 
    justifyContent: "center", 
    gap: "1.5rem",
    width: "100%",
    maxWidth: "600px",
  },
  title: {
    fontSize: "3rem",        
    fontWeight: "bold",
  },
  subtitle: {
    fontSize: "1.6rem",      
    fontWeight: "500",
  },
  packImage: {
    width: "280px",          
    cursor: "pointer",
    transition: "transform 0.2s ease",
  },
  packImageHover: {
    transform: "scale(1.05)",
  },
  packImageWiggle: {
    animation: "wiggle 0.6s ease",
  },
  '@keyframes wiggle': {
    '0%': { transform: 'rotate(0deg)' },
    '15%': { transform: 'rotate(3deg)' },
    '30%': { transform: 'rotate(-3deg)' },
    '45%': { transform: 'rotate(3deg)' },
    '60%': { transform: 'rotate(-3deg)' },
    '75%': { transform: 'rotate(2deg)' },
    '100%': { transform: 'rotate(0deg)' },
  },
  revealCard: {
    border: "1px solid #ccc",
    padding: "1rem",
    borderRadius: "8px",
    width: "220px",
    height: "300px",
    fontSize: "1rem",
    backgroundColor: "#1f1f1f",
    color: "#ffffff",
    boxShadow: "0 2px 5px rgba(0,0,0,0.4)",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  hoveredCard: {
    transform: "scale(1.05) translateY(-5px)",
    boxShadow: "0 0 15px 5px rgba(255, 255, 255, 0.4)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  shakeContainer: {
    animation: "shake 0.4s",
  },
  "@keyframes shake": {
    "0%": { transform: "translate(0px, 0px)" },
    "25%": { transform: "translate(4px, -4px)" },
    "50%": { transform: "translate(-4px, 4px)" },
    "75%": { transform: "translate(4px, -4px)" },
    "100%": { transform: "translate(0px, 0px)" },
  },
  teamGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(6, 1fr)", 
    gridAutoRows: "auto",                 
    gap: "1rem",
    justifyItems: "center",
    alignItems: "start",
    padding: "1rem 2rem",
    marginTop: "1rem",
  },
  outlinedText: {
    textShadow: "-1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000",
  }
}; 